import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.json.JSONObject;
import java.util.ArrayList;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.when;

public class HistoryListModelTest {

    private JsonStorage mockHistory;
    private ArrayList<JSONObject> mockPrompts;

    @BeforeEach
    public void setUp() throws Exception {
        mockHistory = Mockito.mock(JsonStorage.class);
        mockPrompts = new ArrayList<>();

        JSONObject examplePrompt = new JSONObject();
        examplePrompt.put("question", "What is your name?");
        examplePrompt.put("answer", "My name is John.");
        mockPrompts.add(examplePrompt);

        when(mockHistory.getPrompts()).thenReturn(mockPrompts);
        when(mockHistory.getQuestion(anyInt())).thenAnswer(invocation -> {
            int index = invocation.getArgument(0);
            return mockPrompts.get(index).getString("question");
        });
        when(mockHistory.getAnswer(anyInt())).thenAnswer(invocation -> {
            int index = invocation.getArgument(0);
            return mockPrompts.get(index).getString("answer");
        });
    }

    @Test
    public void testPastQuestions() throws Exception {
        HistoryListModel model = new HistoryListModel(mockHistory);
        assertEquals("What is your name?", model.getPastQuestions().get(0));
    }

    @Test
    public void testPastAnswers() throws Exception {
        HistoryListModel model = new HistoryListModel(mockHistory);
        assertEquals("My name is John.", model.getPastAnswers().get(0));
    }

    @Test
    public void testDeleteEntry() throws Exception {
        HistoryListModel model = new HistoryListModel(mockHistory);
        model.deleteEntry(0);
        assertEquals(0, model.getPastQuestions().size());
        assertEquals(0, model.getPastAnswers().size());
    }

    @Test
    public void testClearHistory() throws Exception {
        HistoryListModel model = new HistoryListModel(mockHistory);
        model.clearHistory();
        assertEquals(0, model.getPastQuestions().size());
        assertEquals(0, model.getPastAnswers().size());
    }
}
/*generated by ChatGPT May 12 version, also modified build.gradle to add some dependencies 
 * for Mockito
 */